// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfhleslntdbipqajvmhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmaGxlc2xudGRiaXBxYWp2bWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDk5MjgsImV4cCI6MjA1OTkyNTkyOH0.t8DEdF5dM5i_uP5nCW9D4S8_hNpkx9V5z9YaFGl-xlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);